### ISSUE TITLE
Duvar yerleştirme işlemi

### ISSUE THREAD

**Issue by hurkal** [Emirhansyhan/YilanOyunu#1]
Duvar yerleştirme işlemi neden _DuvaraCarpti()_ içerisinde? Her bir metot tek bir görevi yerine getirirse daha kullanışlı olur.

**Comment by EmirhanSeyhan** [comment]
İlk o şekilde yapmıştım ama bu şekilde bana dazip geldi onun için
değiştirmiştim hocam

23 Oca 2020 Per 23:45 tarihinde Hürkal HÜSEM <notifications@github.com>
şunu yazdı:

**Comment by hurkal** [comment]
Ancak bu durumda, her duvara çarpma işleminin kontrolünde duvarlar yeniden ekleniyor. Oysa form oluşturulduğunda yalnızca bir kez eklenmesi yeterli olacaktır.

**Comment by EmirhanSeyhan** [comment]
Doğru ilk fırsatta değiştireceğim hocam teşekkür ederim uyarınız için .

23 Oca 2020 Per 23:51 tarihinde Hürkal HÜSEM <notifications@github.com>
şunu yazdı:
